export const categories = {
  interior: [
    'Cinema',
    'Kitchen',
    'Bedroom',
    'Garage',
    'Dining Room',
    'Living Room',
    'Study',
    'Gym/Sauna',
    'Pool',
    'Wine Cellar',
    'Bathroom',
    'Overall',
  ],
  exterior: [
    'Garden',
    'Deck',
    'Roof',
    'Driveway',
    'Pool',
    'Pool House',
    'Gate',
    'Overall',
  ],
}

export const filterCategories = {
  interior: [
    'All Categories',
    'Cinema',
    'Kitchen',
    'Bedroom',
    'Garage',
    'Dining Room',
    'Living Room',
    'Study',
    'Gym/Sauna',
    'Pool',
    'Wine Cellar',
    'Bathroom',
    'Overall',
  ],
  exterior: [
    'All Categories',
    'Garden',
    'Deck',
    'Roof',
    'Driveway',
    'Pool',
    'Pool House',
    'Gate',
    'Overall',
  ],
}
